#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Project NeuroFly contributors
"""Measure the composed scenes and write their manifest (standard library only).

    python3 tools/assets/env/measure_scenes.py --out SCENE_DIR --env ENV_DIR --rig RIG_V2_DIR \
        [--write tools/assets/env/SCENES_MANIFEST.json]

Hashes every scene output, records triangles/textures/lights against the phone budget, and the
hashes of the input GLBs each scene was composed from.  Only file names are written.
"""
import argparse
import datetime
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(ASSETS))
sys.path.insert(0, ASSETS)
from measure_assets import glb_metrics, png_size, read_glb, sha256  # noqa: E402

BUDGET = {'scene_triangles': 40000, 'scene_glb_bytes': 3_000_000, 'textures': 0}
SOURCES = ['tools/assets/build_env_scenes.py', 'tools/assets/build_env_scenes_all.sh', 'tools/assets/env/measure_scenes.py',
           'tools/assets/nf_geom.py']


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', required=True)
    ap.add_argument('--env', required=True)
    ap.add_argument('--rig', required=True)
    ap.add_argument('--write', default='')
    a = ap.parse_args()
    scenes, problems = {}, []
    for name in sorted(os.listdir(a.out)):
        if not (name.startswith('scene_') and name.endswith('.glb')):
            continue
        stem = name[:-4]
        p = os.path.join(a.out, name)
        m = glb_metrics(p)
        doc = read_glb(p)
        lights = [l.get('type') for l in doc.get('extensions', {}).get('KHR_lights_punctual', {}).get('lights', [])]
        info = json.load(open(os.path.join(a.out, stem + '.json')))
        files = {}
        for f in sorted(os.listdir(a.out)):
            if f.startswith(stem + '.') or f.startswith(stem + '_'):
                if f.endswith('.blend1'):
                    continue
                fp = os.path.join(a.out, f)
                files[f] = {'sha256': sha256(fp), 'bytes': os.path.getsize(fp)}
                if f.endswith('.png'):
                    files[f]['width'], files[f]['height'] = png_size(fp)
        inputs = {}
        for pl in info['placements']:
            src = os.path.join(a.env if pl['file'].startswith('env_') else a.rig, pl['file'])
            inputs[pl['file']] = sha256(src)
        ok = m['triangles'] <= BUDGET['scene_triangles'] and os.path.getsize(p) <= BUDGET['scene_glb_bytes'] \
            and m['images'] == 0
        if not ok:
            problems.append(f'{name}: over budget')
        scenes[stem] = {'caption': info['caption'], 'status': info['status'], 'triangles': m['triangles'],
                        'glb_bytes': os.path.getsize(p), 'textures': m['textures'], 'images': m['images'],
                        'materials': len(m['materials']), 'lights': lights, 'within_budget': ok,
                        'placements': info['placements'], 'input_glb_sha256': inputs, 'files': files,
                        'bbox_three': [info['bbox_three_min'], info['bbox_three_max']]}
    record = {
        'schema': 'neurofly.presentation-scenes.v1',
        'generated_utc': datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
        'purpose': ('Composed presentation scenes only: pictures, not arenas, stimuli, odour fields, taste contacts '
                    'or encounters. Nothing in them is simulated. The predator scene is ILLUSTRATIVE: no predator '
                    'stimulus or behaviour exists, and it must not change looming or retinal input.'),
        'frame': 'three.js frame, +Y up, viewport-mm (fly display scale); food props at nominal size',
        'dressing': ('original geometry generated by build_env_scenes.py: vertex-coloured soil or lab-plate disc, '
                     'leaf litter, pebbles, twigs, a perch leaf; flies are the W2 rig-v2 LOD1 GLBs in their display '
                     'pose, stood on the surface by their lowest tarsus vertex (preview placement only)'),
        'lighting': 'glTF punctual: warm directional sun + cool point fill; studio area lights are render-only',
        'budgets': {**BUDGET, 'status': 'within budget' if not problems else problems},
        'sources': {s: sha256(os.path.join(REPO, s)) for s in SOURCES if os.path.exists(os.path.join(REPO, s))},
        'scenes': scenes,
        'licences': {'scripts and scene dressing': 'MIT (repository LICENSE); original geometry, no imports',
                     'props and flies': 'MIT, from build_env.py (W3) and build_fly.py rig v2 (W2)',
                     'Blender 4.5.3': 'GPL-2.0-or-later tool; its licence does not apply to output'},
    }
    text = json.dumps(record, indent=2) + '\n'
    if a.write:
        open(a.write, 'w').write(text)
    print(json.dumps({'problems': problems, 'scenes': {k: v['triangles'] for k, v in scenes.items()}}))
    return 1 if problems else 0


if __name__ == '__main__':
    raise SystemExit(main())
